builds:
  - binary: lines
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: lines
    homepage: "https://github.com/axelburling/lines"
    tap:
      owner: axelburling
      name: homebrew-axelburling
    commit_author:
      name: axelburling
      email: axel.burling@gmail.com

checksum:
  name_template: 'checksums.txt'